
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeSet, HashMap},
    env, fs,
    io::Read,
    path::{Path, PathBuf},
};

const FILES: &[&str] = &[
    "click.png",
    "click_mh.png",
    "drag.png",
    "drag_mh.png",
    "flick.png",
    "flick_mh.png",
    "hold.png",
    "hold_mh.png",
    "hit_fx.png",
];

fn sig(tag: &[u8], data: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(tag);
    h.update([0u8]);
    h.update(data);
    h.finalize().into()
}

fn phash(img: &image::DynamicImage) -> [u8; 32] {
    const W: u32 = 16;
    const H: u32 = 16;
    let small = img.resize_exact(W + 1, H, image::imageops::FilterType::Triangle).to_luma8();
    let mut bits = [0u8; 32];
    let mut idx = 0usize;
    for y in 0..H {
        for x in 0..W {
            if small.get_pixel(x, y)[0] < small.get_pixel(x + 1, y)[0] {
                bits[idx / 8] |= 1 << (idx % 8);
            }
            idx += 1;
        }
    }
    bits
}

fn add_pack(files: &HashMap<String, Vec<u8>>, sigs: &mut BTreeSet<[u8; 32]>, phashes: &mut BTreeSet<[u8; 32]>) {

    for (name, bytes) in files {
        sigs.insert(sig(b"raw", bytes));
        if name.ends_with(".png") {
            if let Ok(img) = image::load_from_memory(bytes) {
                let rgba = img.to_rgba8();
                let mut buf = Vec::with_capacity(rgba.as_raw().len() + 8);
                buf.extend_from_slice(&rgba.width().to_le_bytes());
                buf.extend_from_slice(&rgba.height().to_le_bytes());
                buf.extend_from_slice(rgba.as_raw());
                sigs.insert(sig(b"pix", &buf));
                phashes.insert(phash(&img));
            }
        }
    }
}

fn read_zip(path: &Path) -> HashMap<String, Vec<u8>> {
    let mut map = HashMap::new();
    let Ok(file) = fs::File::open(path) else { return map };
    let Ok(mut zip) = zip::ZipArchive::new(file) else { return map };
    for name in FILES {
        if let Ok(mut entry) = zip.by_name(name) {
            let mut b = Vec::new();
            if entry.read_to_end(&mut b).is_ok() {
                map.insert((*name).to_string(), b);
            }
        }
    }
    map
}

fn read_dir_pack(path: &Path) -> HashMap<String, Vec<u8>> {
    let mut map = HashMap::new();
    for name in FILES {
        if let Ok(b) = fs::read(path.join(name)) {
            map.insert((*name).to_string(), b);
        }
    }
    map
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let root = manifest.parent().map(|p| p.to_path_buf()).unwrap_or_else(|| manifest.clone());
    let blacklist = root.join("BLACKLIST");
    println!("cargo:rerun-if-changed={}", blacklist.display());

    let mut sigs: BTreeSet<[u8; 32]> = BTreeSet::new();
    let mut phashes: BTreeSet<[u8; 32]> = BTreeSet::new();
    let mut packs = 0usize;

    if blacklist.is_dir() {
        if let Ok(entries) = fs::read_dir(&blacklist) {
            for entry in entries.flatten() {
                let p = entry.path();
                println!("cargo:rerun-if-changed={}", p.display());
                let files = if p.is_dir() {
                    read_dir_pack(&p)
                } else if p.extension().map_or(false, |e| e.eq_ignore_ascii_case("zip")) {
                    read_zip(&p)
                } else {
                    continue;
                };
                if !files.is_empty() {
                    add_pack(&files, &mut sigs, &mut phashes);
                    packs += 1;
                }
            }
        }
    } else {
        println!(
            "cargo:warning=BLACKLIST folder not found at {} — respack copyright detection will be disabled in this build.",
            blacklist.display()
        );
    }

    println!(
        "cargo:warning=respack blacklist: {} pack(s), {} signature(s), {} perceptual hash(es) embedded.",
        packs,
        sigs.len(),
        phashes.len()
    );

    let emit = |name: &str, set: &BTreeSet<[u8; 32]>| {
        let mut s = format!("pub static {name}: &[[u8; 32]] = &[\n");
        for h in set {
            s.push_str("    [");
            for (i, b) in h.iter().enumerate() {
                if i > 0 {
                    s.push(',');
                }
                s.push_str(&b.to_string());
            }
            s.push_str("],\n");
        }
        s.push_str("];\n");
        s
    };

    let mut src = String::new();
    src.push_str("// @generated by build.rs from the BLACKLIST/ folder. Do not edit.\n");
    src.push_str(&emit("BLACKLIST_SIGS", &sigs));
    src.push_str(&emit("BLACKLIST_PHASHES", &phashes));

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("blacklist_gen.rs");
    fs::write(&out, src).unwrap();
}
