use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Key, Nonce,
};
use std::{env, fs, path::Path};

fn git_stdout(args: &[&str]) -> Option<String> {
    let output = std::process::Command::new("git").args(args).output().ok()?;
    if !output.status.success() {
        return None;
    }
    let stdout = std::str::from_utf8(&output.stdout).ok()?.trim().to_string();
    if stdout.is_empty() {
        None
    } else {
        Some(stdout)
    }
}

const FEAT_ID_KEY: &[u8; 32] = b"FeatId\xb8\x2f\x7a\xc1\x55\x3e\x90\xd4\x08\x6b\xf2\
                                  \x19\x4c\x87\xe3\x2a\x71\xbc\x0f\x9d\x64\x38\xc5\xe7\xa1\xd2";

const FEATURES: &[(u32, &str)] = &[
    (54729831, "Dark Theme (Windows 10 Style)"),
    (82647139, "Custom Background"),
    (63815247, "Custom BGM"),
];

fn encrypt_ids(out_dir: &str) {
    let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(FEAT_ID_KEY));

    let mut entries = Vec::new();
    for (i, &(code, label)) in FEATURES.iter().enumerate() {

        let mut nonce_bytes = [0u8; 12];
        nonce_bytes[11] = i as u8;
        let nonce = Nonce::from_slice(&nonce_bytes);

        let plaintext = code.to_le_bytes();
        let ciphertext = cipher.encrypt(nonce, plaintext.as_ref()).expect("encrypt");

        let nonce_lit = byte_array_literal(&nonce_bytes);
        let ct_lit = byte_array_literal(&ciphertext);
        entries.push(format!(
            "    (&{nonce_lit}, &{ct_lit}, \"{label}\")",
        ));
    }

    let src = format!(
        "// Generated by build.rs — do not edit.\n\
         // Contains AES-256-GCM ciphertexts of feature unlock codes.\n\
         pub(crate) static ENCRYPTED_FEAT_IDS: &[(&[u8], &[u8], &str)] = &[\n{}\n];\n",
        entries.join(",\n")
    );

    fs::write(Path::new(out_dir).join("unlock_ids.rs"), src)
        .expect("write unlock_ids.rs");
}

fn byte_array_literal(bytes: &[u8]) -> String {
    let inner: Vec<String> = bytes.iter().map(|b| format!("0x{b:02x}")).collect();
    format!("[{}]", inner.join(", "))
}

fn main() {
    dotenv_build::output(dotenv_build::Config::default()).unwrap();

    let git_dir = git_stdout(&["rev-parse", "--git-dir"]).unwrap_or_else(|| ".git".to_string());
    println!("cargo:rerun-if-changed={}/HEAD", git_dir);
    println!("cargo:rerun-if-changed={}/packed-refs", git_dir);

    if let Some(ref_path) = git_stdout(&["symbolic-ref", "-q", "HEAD"]) {
        println!("cargo:rerun-if-changed={}/{}", git_dir, ref_path);
    }

    let git_hash = git_stdout(&["rev-parse", "--short=7", "HEAD"])
        .unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=GIT_HASH={}", git_hash);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    encrypt_ids(&out_dir);
    println!("cargo:rerun-if-changed=build.rs");
}
